project:
  type: website

website:
  title: "Jack Huber"
  navbar:
    right:
      - href: talks.qmd
        text: "Talks"
      - href: pubs.qmd
        text: "Publications"
      - href: teaching.qmd
        text: "Teaching"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

