---
title: "Publications"
editor: visual
---

------------------------------------------------------------------------

## Professional Journals

Monpas-Huber, J.B. (2015). Just pressing buttons? Validity evidence for the STAR and Smarter Balanced Summative Assessments. *The WERA Educational Journal*, 8(1), pp. 39-44. Washington Educational Research Association (WERA)

Monpas-Huber, J.B. (2013). Assessing teacher effectiveness: Charlotte Danielson's presentation at the December 2012 WERA Conference. *The Standard Deviation Newsletter*, pp. 12-13. Washington Educational Research Association (WERA)

Monpas-Huber, J.B. (2011). Validity of college and career readiness assessments. *The WERA Educational Journal*, 4(1), pp. 10-12. Washington Educational Research Association (WERA)

\* Monpas-Huber, J.B. (2010). Explaining high school teachers instructional use of state assessment data: A multilevel study from Washington State. *Journal of School Leadership*, 20(2), pp. 208-237.

Monpas-Huber, J.B. (2009). Aligning district and state assessments to measure growth in achievement. *The WERA Educational Journal*, 1(1), pp. 47-50. Washington Educational Research Association (WERA)

De Leeuw, H., & Monpas-Huber, J.B. (2009). Achievement of English Language Learners. Leadership Information, 7(3), pp. 1-23. *School Information and Research Service*, Washington Association of School Administrators (WASA)

Monpas-Huber, J.B. (2008). Validity issues for common district assessments. *The Standard Deviation Newsletter*, pp. 20-29. Washington Educational Research Association (WERA)

## Co-authored Occasional Paper

Knapp, M.S., Swinnerton, J.A., Copland, M.A., & **Monpas-Huber, J.B.** (2006). [Data-informed leadership in education](https://www.education.uw.edu/ctp/sites/default/files/ctpmail/PDFs/DataInformed-N...). Seattle, WA: Center for the Study of Teaching and Policy, University of Washington

## Doctoral Dissertation

Monpas-Huber, J.B. (2007). Context and motivation to use state assessment data: A multilevel study of high school teachers in Washington State. Doctoral Dissertation. College of Education, University of Washington, Seattle, WA
