---
title: "Talks"
editor: visual
---

------------------------------------------------------------------------

Huber, J.B. (2018). Bias in standardized testing. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Huber, J.B. (2018). A closer look at summer change: Lessons from longitudinal data. Summer Fusion Conference of Northwest Evaluation Association (NWEA), Portland, OR.

Monpas-Huber, J.B. (2015). The relationship between Fountas & Pinnell Benchmark Assessment System and Smarter Balanced English and Language Arts Assessments, Grades 3-5. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Monpas-Huber, J.B. (2015). Just pressing buttons? Validity evidence for the STAR Assessments and Smarter Balanced Summative Assessments. Presented at the Washington State School Directors Association (WSSDA) Conference, Bellevue, WA.

Monpas-Huber, J.B., & Garrett, M. (2012). The course challenge test: A catalyst for change? Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Monpas-Huber, J.B. (2012). Growth inferences from district and state assessments: A look at elementary reading. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Monpas-Huber, K., & Monpas-Huber, J.B. (2011). The role of reading strategies in middle school reading comprehension: A classroom-based action research project. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Alonzo, J., Monpas-Huber, J.B., & Henry, S. (2010). Increasing student achievement with response to intervention and curriculum-based measurement. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Cummings, P., Monpas-Huber, J.B., & Wakeley, D. (2009). Tricks of the trade: Data displays for assessment directors. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Monpas-Huber, J.B., & Henry, S. (2009). Using data from common district assessments to inform decisions about middle school mathematics: Lessons from Shoreline Public Schools. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Monpas-Huber, J.B., & Cummings, P. (2009). The how and why of podcasting for assessment folks. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA.

Monpas-Huber, J.B. (2009). Building a data dashboard: The role of research. Presented at the March Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

Monpas-Huber, J. B. (2008). Aligning assessments to monitor growth in mathematics achievement: A validity study. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

Monpas-Huber, J.B. (2008). High school teachers' use of data: A multilevel study. Presented at the Annual Meeting of the American Educational Research Association (WERA), New York, NY.

De Leeuw, H. & Monpas-Huber, J.B. (2007). WASL performance of exited English language learners: Interesting findings and possible explanations. Presented at December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

Oakley, D., Lindeblad, K., Rye, G., Dennis, K., & Monpas-Huber, J.B. (2007). Using district assessments to improve mathematics instruction: The experience of Spokane Public Schools. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

Monpas-Huber, J.B. (2007). Validity issues for medium-scale district assessments. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

De Leeuw, H. & Monpas-Huber, J.B. (2007). Exited English language learners outperforming the district on state assessment: How can this be? Presented at the April Meeting of the Washington Association of Bilingual Education (WABE), Toppenish, WA.

Monpas-Huber, J.B. (2007). Making sense of assessment data: A case study of high school leaders. Presented at the Annual Meeting of the American Educational Research Association (AERA), Chicago, IL.

Monpas-Huber, J.B. (2006). High school teachers instructional use of state assessment data: Exploring the role of school culture and motivation. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

Silverman, R., Elman, L., & Monpas-Huber, J.B. (2005). Alternative views of state assessment (WASL) data. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.

Monpas-Huber, J.B. (2002). The impact of school grade configuration on state assessment (WASL) performance. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA.
